### ISSUE TITLE
congruence and xtuple-query

### ISSUE THREAD

**Issue by BryIsAZombie** [tjwebb/congruence#9]
Hey, TJ

Looking through your congruence/[xtuple-query](https://github.com/tjwebb/xtuple-query) code and trying to do something similar. I noticed xtuple-query uses an older version of congruence that has an "or" function to support using an array as a predicate. That was removed in this [commit](https://github.com/tjwebb/congruence/commit/1a996f40145ed2adba55238979aa70b854e3dd13).

I'm wanting to use the latest version of congruence but can't quite figure out how you replaced the "or" method. From what I can tell you didn't, and you expect the user to write their own "or" predicate. Is this assumption correct or am I missing something?

A good example of what I am trying to achieve is something similar to this [template](https://github.com/tjwebb/xtuple-query/blob/master/lib/RestQuery.js#L51-L78).

**Comment by tjwebb** [comment]
Between 1.5.x and 1.6.x I removed a lot of complexity, which included that custom syntax, and the `_.or` function. You can implement the same thing just using lodash `_.any`: https://lodash.com/docs#some

**Comment by tjwebb** [comment]
Does this example help?

https://github.com/tjwebb/congruence/blob/master/test.js#L396-L418

**Comment by BryIsAZombie** [comment]
Yea, helped a lot. Thanks for the quick reply.
